[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "echo \"Admin Email : $ADMIN_EMAIL\" && python3 ./manage.py registeradmin $ADMIN_EMAIL && ./entrypoint.sh"

