[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "$( $(python manage.py registeradmin test@sdddexample.com) || true ) && ./entrypoint.sh"
